name: agenticseek-backend
services:
- name: api
  github:
    branch: main
    deploy_on_push: true
    repo: CleanExpo/agenticseek
  source_dir: .
  dockerfile_path: Dockerfile
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: PYTHON_VERSION
    value: "3.12"
  - key: PORT
    value: "8000"
  - key: ENVIRONMENT
    value: "production"
  - key: CORS_ORIGINS
    value: "https://agenticseek.vercel.app"
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 60 